source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`.
# Run Jekyll with `bundle exec jekyll serve` to build and serve your site.
# For more information on the Gemfile, see https://jekyllrb.com/docs/themes/#installing-a-theme

# This is the default theme for new Jekyll sites. It may be updated
# with Jekyll or gem updates. You can also replace it with another
# theme or remove it to use the default Jekyll theme.

gem "jekyll", "~> 4.3"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

# Windows and JRuby compatibility
platforms :ruby do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance booster for watching directories on Windows
gem "wdm", "~> 0.1" if Gem.win_platform?

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions
# of the gem will not work on JRuby (see https://github.com/jekyll/jekyll/issues/8524)
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
