#!/bin/bash
# IoTDB Enhanced - Production Setup Script
# This script helps configure the application for production deployment

set -e

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║        IoTDB Enhanced - Production Environment Setup                 ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root (use sudo)${NC}"
    exit 1
fi

PROJECT_ROOT="/root"
BACKEND_ENV="$PROJECT_ROOT/backend/.env"
PM2_CONFIG="$PROJECT_ROOT/ecosystem.config.cjs"

# Generate secure secrets
echo -e "${GREEN}[1/5] Generating secure secrets...${NC}"
JWT_SECRET=$(openssl rand -base64 64)
SESSION_SECRET=$(openssl rand -base64 64)
IOTDB_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)

echo "JWT_SECRET: $JWT_SECRET"
echo "SESSION_SECRET: $SESSION_SECRET"
echo "IOTDB_PASSWORD: $IOTDB_PASSWORD"

# Save secrets to file
cat > "$PROJECT_ROOT/.production-secrets" << EOF
# Production Secrets - Generated on $(date)
JWT_SECRET=$JWT_SECRET
SESSION_SECRET=$SESSION_SECRET
IOTDB_PASSWORD=$IOTDB_PASSWORD
EOF
chmod 600 "$PROJECT_ROOT/.production-secrets"
echo -e "${GREEN}✓ Secrets saved to $PROJECT_ROOT/.production-secrets${NC}"
echo ""

# Ask for IoTDB connection details
echo -e "${YELLOW}[2/5] IoTDB Configuration${NC}"
read -p "IoTDB Host [localhost]: " IOTDB_HOST
IOTDB_HOST=${IOTDB_HOST:-localhost}

read -p "IoTDB RPC Port [6667]: " IOTDB_PORT
IOTDB_PORT=${IOTDB_PORT:-6667}

read -p "IoTDB REST Port [18080]: " IOTDB_REST_PORT
IOTDB_REST_PORT=${IOTDB_REST_PORT:-18080}

read -p "Create new IoTDB user 'iotdb_app'? [Y/n]: " CREATE_USER
CREATE_USER=${CREATE_USER:-Y}

if [[ "$CREATE_USER" =~ ^[Yy]$ ]]; then
    echo ""
    echo "To create the IoTDB user, run these commands in IoTDB CLI:"
    echo ""
    echo -e "${GREEN}CREATE USER iotdb_app WITH PASSWORD '$IOTDB_PASSWORD';${NC}"
    echo -e "${GREEN}GRANT ADMIN ON root TO iotdb_app;${NC}"
    echo ""
    read -p "Press Enter after creating the user..."
fi
echo ""

# Update backend .env file
echo -e "${YELLOW}[3/5] Updating backend environment...${NC}"

if [ -f "$BACKEND_ENV" ]; then
    # Backup existing .env
    cp "$BACKEND_ENV" "$BACKEND_ENV.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Create or update .env
cat > "$BACKEND_ENV" << 'EOF'
# IoTDB Enhanced - Backend Environment Configuration
# Generated by setup-production.sh

# Server Configuration
NODE_ENV=production
PORT=8000

# Database Configuration
DATABASE_URL="postgresql://iotdb_user:your_db_password@localhost:5432/iotdb_enhanced"

# Redis Configuration
REDIS_URL="redis://localhost:6379"
REDIS_PASSWORD=your_redis_password

# IoTDB Configuration
IOTDB_HOST=localhost
IOTDB_PORT=6667
IOTDB_USERNAME=iotdb_app
IOTDB_PASSWORD=your_iotdb_password
IOTDB_REST_URL=http://localhost:18080

# AI Configuration
IOTDB_AI_ENABLED=false

# Security Configuration
JWT_SECRET=your_jwt_secret_here
SESSION_SECRET=your_session_secret_here

# Email Configuration (optional)
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USER=noreply@example.com
SMTP_PASSWORD=your_smtp_password
SMTP_FROM="IoTDB Enhanced <noreply@example.com>"

# Application Configuration
APP_URL=https://your-domain.com
CORS_ORIGIN=https://your-domain.com

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
EOF

# Replace with generated values
sed -i "s|your_jwt_secret_here|$JWT_SECRET|g" "$BACKEND_ENV"
sed -i "s|your_session_secret_here|$SESSION_SECRET|g" "$BACKEND_ENV"
sed -i "s|IOTDB_HOST=localhost|IOTDB_HOST=$IOTDB_HOST|g" "$BACKEND_ENV"
sed -i "s|IOTDB_PORT=6667|IOTDB_PORT=$IOTDB_PORT|g" "$BACKEND_ENV"
sed -i "s|your_iotdb_password|$IOTDB_PASSWORD|g" "$BACKEND_ENV"
sed -i "s|IOTDB_REST_URL=http://localhost:18080|IOTDB_REST_URL=http://$IOTDB_HOST:$IOTDB_REST_PORT|g" "$BACKEND_ENV"

chmod 600 "$BACKEND_ENV"
echo -e "${GREEN}✓ Backend .env updated${NC}"
echo ""

# Update PM2 configuration
echo -e "${YELLOW}[4/5] Updating PM2 configuration...${NC}"

# Backup PM2 config
cp "$PM2_CONFIG" "$PM2_CONFIG.backup.$(date +%Y%m%d_%H%M%S)"

# Update to production mode
sed -i "s/NODE_ENV: 'development'/NODE_ENV: 'production'/g" "$PM2_CONFIG"

echo -e "${GREEN}✓ PM2 configuration updated to production mode${NC}"
echo ""

# Rebuild and restart
echo -e "${YELLOW}[5/5] Rebuilding and restarting services...${NC}"
echo ""

read -p "Rebuild backend? [Y/n]: " REBUILD_BACKEND
REBUILD_BACKEND=${REBUILD_BACKEND:-Y}

if [[ "$REBUILD_BACKEND" =~ ^[Yy]$ ]]; then
    echo "Rebuilding backend..."
    cd "$PROJECT_ROOT/backend"
    npm run build
fi

read -p "Rebuild frontend? [Y/n]: " REBUILD_FRONTEND
REBUILD_FRONTEND=${REBUILD_FRONTEND:-Y}

if [[ "$REBUILD_FRONTEND" =~ ^[Yy]$ ]]; then
    echo "Rebuilding frontend..."
    cd "$PROJECT_ROOT/frontend"
    npm run build
fi

read -p "Restart PM2 services? [Y/n]: " RESTART_PM2
RESTART_PM2=${RESTART_PM2:-Y}

if [[ "$RESTART_PM2" =~ ^[Yy]$ ]]; then
    echo "Restarting PM2..."
    cd "$PROJECT_ROOT"
    pm2 reload ecosystem.config.cjs --env production
    pm2 save

    echo ""
    echo -e "${GREEN}Current PM2 status:${NC}"
    pm2 status
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                    Production Setup Complete!                        ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}✓ Security secrets generated and saved${NC}"
echo -e "${GREEN}✓ Backend environment configured${NC}"
echo -e "${GREEN}✓ PM2 configuration updated${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Configure PostgreSQL database and update DATABASE_URL"
echo "2. Configure Redis with password and update REDIS_PASSWORD"
echo "3. Update APP_URL and CORS_ORIGIN with your domain"
echo "4. Configure SMTP settings for email notifications"
echo "5. Run: pm2 logs iotdb-backend to verify startup"
echo ""
echo -e "${YELLOW}Security reminders:${NC}"
echo "- Keep .production-secrets file secure and backed up"
echo "- Never commit secrets to git"
echo "- Use strong, unique passwords for production"
echo "- Enable HTTPS/TLS for all services"
echo "- Set up regular database backups"
echo ""
